<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.554">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Rodney X. Sturdivant, Ph.D.">
<meta name="dcterms.date" content="2024-07-01">
<meta name="description" content="Computing sample size for studies involving tennis">

<title>Baylor APU SCORE Module Preprint Repository - Tennis Sample Size</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/cookie-consent/cookie-consent.js"></script>
<link href="../../site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-JVDQHPRYT1"></script>

<script type="text/plain" cookie-consent="tracking">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-JVDQHPRYT1', { 'anonymize_ip': true});
</script>

<script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"simple",
  "consent_type":"implied",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary","functionality","tracking","targeting"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  ,
"language":"en"
  });
});
</script> 
  

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating nav-fixed slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Baylor APU SCORE Module Preprint Repository</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../../by-statsds-topic.html" aria-current="page"> 
<span class="menu-text">Modules By Topic</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://data.scorenetwork.org/"> 
<span class="menu-text">Data Repository</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../tennis/tennis_sampsize/index.html">Tennis</a></li><li class="breadcrumb-item"><a href="../../tennis/tennis_sampsize/index.html">Tennis Sample Size</a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../by-statsds-topic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Modules By Topic</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
 <span class="menu-text">Anw</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../anw/kaplan_meier/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">American Ninja Warrior - Kaplan-Meier Survival Analyis</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
 <span class="menu-text">Baseball</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../baseball/mlb_injuries/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">MLB Injuries - Introductory Time Series Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../baseball/mlb_prime_age/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">What’s the prime age of an MLB player?</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">
 <span class="menu-text">Golf</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../golf/pga_gir/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PGA - Scheffler Greens in Regulation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../golf/pga_gir_nor/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PGA - Scheffler Greens in Regulation (No R)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../golf/pga_masters/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PGA - Scoring Average Confidence Intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../golf/pga_masters_nor/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PGA - Scoring Average Confidence Intervals (No R)</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false">
 <span class="menu-text">Mma</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../mma/mma_chisquare/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">MMA Fight Decisions</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false">
 <span class="menu-text">Soccer</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../soccer/mls_decision_errors/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">MLS - Types of Decision Errors</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
 <span class="menu-text">Tennis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../tennis/tennis_sampsize/index.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Tennis Sample Size</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="false">
 <span class="menu-text">Volleyball</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../volleyball/ncaa_d1/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Volleyball - Women’s NCAA Division I</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#welcome-video" id="toc-welcome-video" class="nav-link active" data-scroll-target="#welcome-video">Welcome video</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#getting-started-tennis-data" id="toc-getting-started-tennis-data" class="nav-link" data-scroll-target="#getting-started-tennis-data">Getting started: Tennis data</a>
  <ul class="collapse">
  <li><a href="#tennis-data-overview" id="toc-tennis-data-overview" class="nav-link" data-scroll-target="#tennis-data-overview">Tennis Data Overview</a></li>
  <li><a href="#variable-descriptions" id="toc-variable-descriptions" class="nav-link" data-scroll-target="#variable-descriptions">Variable descriptions</a></li>
  <li><a href="#viewing-your-data" id="toc-viewing-your-data" class="nav-link" data-scroll-target="#viewing-your-data">Viewing your data</a></li>
  </ul></li>
  <li><a href="#sample-size-overview" id="toc-sample-size-overview" class="nav-link" data-scroll-target="#sample-size-overview">Sample Size Overview</a>
  <ul class="collapse">
  <li><a href="#why-does-sample-size-matter" id="toc-why-does-sample-size-matter" class="nav-link" data-scroll-target="#why-does-sample-size-matter">Why does sample size matter</a>
  <ul class="collapse">
  <li><a href="#types-of-errors" id="toc-types-of-errors" class="nav-link" data-scroll-target="#types-of-errors">Types of errors</a></li>
  <li><a href="#balancing-the-errors" id="toc-balancing-the-errors" class="nav-link" data-scroll-target="#balancing-the-errors">Balancing the errors</a></li>
  </ul></li>
  <li><a href="#factors-impacting-sample-size-power" id="toc-factors-impacting-sample-size-power" class="nav-link" data-scroll-target="#factors-impacting-sample-size-power">Factors impacting sample size (power)</a></li>
  </ul></li>
  <li><a href="#example-1-power-for-two-sample-t-test" id="toc-example-1-power-for-two-sample-t-test" class="nav-link" data-scroll-target="#example-1-power-for-two-sample-t-test">Example 1: Power for two sample t-test</a>
  <ul class="collapse">
  <li><a href="#estimating-the-parameters" id="toc-estimating-the-parameters" class="nav-link" data-scroll-target="#estimating-the-parameters">Estimating the Parameters</a></li>
  <li><a href="#computing-the-sample-size" id="toc-computing-the-sample-size" class="nav-link" data-scroll-target="#computing-the-sample-size">Computing the Sample Size</a></li>
  </ul></li>
  <li><a href="#example-2-power-for-two-sample-test-of-proportions" id="toc-example-2-power-for-two-sample-test-of-proportions" class="nav-link" data-scroll-target="#example-2-power-for-two-sample-test-of-proportions">Example 2: Power for two sample test of proportions</a>
  <ul class="collapse">
  <li><a href="#estimating-the-parameters-1" id="toc-estimating-the-parameters-1" class="nav-link" data-scroll-target="#estimating-the-parameters-1">Estimating the Parameters</a></li>
  <li><a href="#computing-the-sample-size-1" id="toc-computing-the-sample-size-1" class="nav-link" data-scroll-target="#computing-the-sample-size-1">Computing the Sample Size</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">REFERENCES</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../tennis/tennis_sampsize/index.html">Tennis</a></li><li class="breadcrumb-item"><a href="../../tennis/tennis_sampsize/index.html">Tennis Sample Size</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Tennis Sample Size</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Sample size</div>
    <div class="quarto-category">Power</div>
    <div class="quarto-category">Independent two sample t-test</div>
    <div class="quarto-category">Independent two sample test of proportions</div>
    <div class="quarto-category">Hypotheses testing</div>
    <div class="quarto-category">Types of errors</div>
  </div>
  </div>

<div>
  <div class="description">
    Computing sample size for studies involving tennis
  </div>
</div>

<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Rodney X. Sturdivant, Ph.D. <a href="mailto:Rodney_Sturdivant@baylor.edu" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Baylor University
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 1, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Facilitation notes">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Facilitation notes
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><p>This module would be suitable for an in-class lab or take-home assignment in an introductory statistics course.</p></li>
<li><p>It assumes a basic familiarity with the RStudio Environment has already been covered, but no prior programming experiences is expected.</p></li>
<li><p>Students should be provided with the following data file (.csv) and Quarto document (.qmd) to produce tests/visualizations and write up their answers to each exercise. Their final deliverable is to turn in an .html document produced by “Rendering” the .qmd.</p>
<ul>
<li><a href="wimbledon_featured_matches.csv">data</a></li>
<li><a href="tennis_student_template.qmd">Student Quarto template</a></li>
</ul></li>
<li><p><a href="https://posit.cloud/">Posit Cloud</a> (via an Instructor account) or <a href="https://classroom.github.com">Github classroom</a> are good options for disseminating files to students, but simply uploading files to your university’s course management system works, too.</p></li>
</ul>
</div>
</div>
</div>
<section id="welcome-video" class="level1">
<h1>Welcome video</h1>
<iframe width="560" height="315" src="" title="placeholder">
</iframe>
</section>
<section id="introduction" class="level1 page-columns page-full">
<h1>Introduction</h1>
<p>In this module, you will compute the required sample size for studies involving tennis data, using data from Wimbledon 2023 matches to estimate required parameters.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Learning Objectives">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Learning Objectives
</div>
</div>
<div class="callout-body-container callout-body">
<p>By the end of this module, you will be able to:</p>
<ul>
<li><p>Read (import) a dataset into your RStudio Environment</p></li>
<li><p>Use R to obtain estimates for various parameters from existing data</p></li>
<li><p>Compute sample size/power for studies involving:</p>
<ul>
<li><p>Independent two sample t-test</p></li>
<li><p>Independent two sample test of proportions</p></li>
</ul></li>
<li><p>Understand basic principles for sample size and power analysis</p></li>
</ul>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p><br>
<br>
<br>
<br>
</p>
<p><strong>NOTE</strong>: <strong>R</strong> is the name of the programming language itself and <strong>RStudio</strong> is a convenient interface. To throw even more lingo in, you may be accessing RStudio through a web-based version called <strong>Posit Cloud</strong>. But R is the programming language you are learning :)</p>
</div></div><div class="callout callout-style-default callout-caution no-icon callout-titled" title="Research Questions">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Research Questions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>During this lab, you’ll investigate the following research questions:</p>
<ul>
<li>What sample size is required for a study of the differences in running distances for tennis players on clay and grass courts</li>
<li>What sample size is required for a study of the differences in percentage of points won on the first serve for tennis players on clay and grass courts</li>
</ul>
</div>
</div>
</div>
</section>
<section id="getting-started-tennis-data" class="level1 page-columns page-full">
<h1>Getting started: Tennis data</h1>
<p>The first step to any analysis in R is to <strong>load necessary packages and data</strong>.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>You can think of <strong>packages</strong> like apps on your phone; they extend the functionality and give you access to many more features beyond what comes in the “base package”.</p>
</div></div><p>Running the following code will load the <code>tidyverse</code> package, and the <code>tennis</code> data we will be using in this lab.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p><strong>TIP</strong>: As you follow along in the lab, you should run each corresponding code chunk in your .qmd document. To “Run” a code chunk, you can press the green “Play” button in the top right corner of the code chunk in your .qmd. You can also place your cursor anywhere in the line(s) of code you want to run and press “command + return” (Mac) or “Ctrl + Enter” (Windows).</p>
</div><div class="">
<p><strong>TIP</strong>: Using a hashtag in R allows you to add comments to your code (in plain English). Data scientists often use comments to explain what each piece of the code is doing.</p>
</div></div>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co">#loads package</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DescTools)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effectsize)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pwr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>tennis <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"wimbledon_featured_matches.csv"</span>) <span class="co">#loads data</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can use the <code>glimpse()</code> function to get a quick look (errr.. glimpse) at our <code>tennis</code> data. The <code>glimpse</code> code provides the number of observations (Rows) and the number of variables (Columns) in the dataset. The “Rows” and “Columns” are referred to as the <strong>dimensions</strong> of the dataset. It also shows us the names of the variables (<code>match_id</code>, <code>player1</code>, …, <code>return_depth</code>) and the first few observations for each variable (e.g.&nbsp;the first match in the dataset has id “1301” and was Carlos Alcaraz playing Nicolas Jarry).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(tennis)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 7,284
Columns: 46
$ match_id           &lt;chr&gt; "2023-wimbledon-1301", "2023-wimbledon-1301", "2023…
$ player1            &lt;chr&gt; "Carlos Alcaraz", "Carlos Alcaraz", "Carlos Alcaraz…
$ player2            &lt;chr&gt; "Nicolas Jarry", "Nicolas Jarry", "Nicolas Jarry", …
$ elapsed_time       &lt;time&gt; 00:00:00, 00:00:38, 00:01:01, 00:01:31, 00:02:21, …
$ set_no             &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ game_no            &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, …
$ point_no           &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, …
$ p1_sets            &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ p2_sets            &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ p1_games           &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, …
$ p2_games           &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ p1_score           &lt;chr&gt; "0", "0", "15", "15", "30", "40", "40", "AD", "40",…
$ p2_score           &lt;chr&gt; "0", "15", "15", "30", "30", "30", "40", "40", "40"…
$ server             &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, …
$ serve_no           &lt;dbl&gt; 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, …
$ point_victor       &lt;dbl&gt; 2, 1, 2, 1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 2, 2, 1, 2, …
$ p1_points_won      &lt;dbl&gt; 0, 1, 1, 2, 3, 3, 4, 4, 5, 6, 6, 7, 8, 8, 8, 9, 9, …
$ p2_points_won      &lt;dbl&gt; 1, 1, 2, 2, 2, 3, 3, 4, 4, 4, 5, 5, 5, 6, 7, 7, 8, …
$ game_victor        &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, …
$ set_victor         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ p1_ace             &lt;dbl&gt; 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ p2_ace             &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, …
$ p1_winner          &lt;dbl&gt; 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ p2_winner          &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, …
$ winner_shot_type   &lt;chr&gt; "0", "0", "0", "F", "0", "0", "0", "F", "0", "0", "…
$ p1_double_fault    &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ p2_double_fault    &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ p1_unf_err         &lt;dbl&gt; 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ p2_unf_err         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, …
$ p1_net_pt          &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, …
$ p2_net_pt          &lt;dbl&gt; 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ p1_net_pt_won      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, …
$ p2_net_pt_won      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ p1_break_pt        &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ p2_break_pt        &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ p1_break_pt_won    &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ p2_break_pt_won    &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ p1_break_pt_missed &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ p2_break_pt_missed &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ p1_distance_run    &lt;dbl&gt; 6.000, 5.253, 13.800, 51.108, 0.649, 5.291, 6.817, …
$ p2_distance_run    &lt;dbl&gt; 7.840, 7.094, 19.808, 75.631, 0.813, 4.249, 17.821,…
$ rally_count        &lt;dbl&gt; 2, 1, 4, 13, 1, 2, 1, 6, 7, 5, 1, 4, 4, 3, 1, 2, 1,…
$ speed_mph          &lt;dbl&gt; 95, 118, 120, 130, 112, 97, 109, 105, 128, 110, 112…
$ serve_width        &lt;chr&gt; "BC", "B", "B", "BW", "W", "BW", "W", "B", "BC", "B…
$ serve_depth        &lt;chr&gt; "NCTL", "CTL", "NCTL", "CTL", "NCTL", "NCTL", "CTL"…
$ return_depth       &lt;chr&gt; "ND", "ND", "D", "D", NA, "ND", "D", "ND", "D", "ND…</code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p><strong>ERROR?</strong> Did you get a error message that says <code>could not find function "glimpse"</code>? This means you need to load the <code>tidyverse</code> package. You can do this by running the code <code>library(tidyverse)</code> from the previous code chunk. A shortcut is to hit the “fast-forward” button (next to the “Play” button in your code chunk), which will run all code chunks above your current one.</p>
</div></div><section id="tennis-data-overview" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="tennis-data-overview">Tennis Data Overview</h2>
<p>Before proceeding with any analysis, let’s make sure we understand what information is contained for key variables (column) in our dataset.</p>
<p>The data set is from the 2023 Men’s Singles Wimbledon Championships, perhaps the most important tennis tournament each year.</p>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Basic Features of the Wimbledon 2023 data
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Wimbledon is a single elimination tournament
<ul>
<li>Round 1 begins with 128 players; 64 matches are played with the 64 winning players advancing to the second round.</li>
<li>Subsequent rounds are played until two players reach the final; the winner of this final round is the Wimbledon Champion</li>
</ul></li>
<li>Our tennis data set includes all matches after the second round.</li>
<li>The data provides information for every point played in the matches
<ul>
<li>Each row represents a point</li>
<li>Points are ordered within each match from the first to last point</li>
</ul></li>
</ul>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>Totally new to Tennis? See this site: <a href="https://www.sportingnews.com/us/tennis/news/tennis-scoring-explained-rules-system-points-terms/7uzp2evdhbd11obdd59p3p1cx">INTRODUCTION TO TENNIS SCORING</a></p>
</div><div class="">
<p>For more information about Wimbledon: <a href="https://www.wimbledon.com/index.html">Wimbledon Official Site</a></p>
</div></div>
</section>
<section id="variable-descriptions" class="level2">
<h2 class="anchored" data-anchor-id="variable-descriptions">Variable descriptions</h2>
<p>We will actually only use a few columns for this module, but the full description of the data is provided. Some variables have data for both players with columns with labels starting “p1” for player 1 and “p2” for player two. We define these for player 1, but the definitions hold for the corresponding player 2 variables.</p>
<details>
<div class="cell">
<div class="cell-output-display">
<div>
<div id="vchwiftxdc" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#vchwiftxdc table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#vchwiftxdc thead, #vchwiftxdc tbody, #vchwiftxdc tfoot, #vchwiftxdc tr, #vchwiftxdc td, #vchwiftxdc th {
  border-style: none;
}

#vchwiftxdc p {
  margin: 0;
  padding: 0;
}

#vchwiftxdc .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#vchwiftxdc .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#vchwiftxdc .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#vchwiftxdc .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#vchwiftxdc .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#vchwiftxdc .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#vchwiftxdc .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#vchwiftxdc .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#vchwiftxdc .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#vchwiftxdc .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#vchwiftxdc .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#vchwiftxdc .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#vchwiftxdc .gt_spanner_row {
  border-bottom-style: hidden;
}

#vchwiftxdc .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#vchwiftxdc .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#vchwiftxdc .gt_from_md > :first-child {
  margin-top: 0;
}

#vchwiftxdc .gt_from_md > :last-child {
  margin-bottom: 0;
}

#vchwiftxdc .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#vchwiftxdc .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#vchwiftxdc .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#vchwiftxdc .gt_row_group_first td {
  border-top-width: 2px;
}

#vchwiftxdc .gt_row_group_first th {
  border-top-width: 2px;
}

#vchwiftxdc .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#vchwiftxdc .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#vchwiftxdc .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#vchwiftxdc .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#vchwiftxdc .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#vchwiftxdc .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#vchwiftxdc .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#vchwiftxdc .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#vchwiftxdc .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#vchwiftxdc .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#vchwiftxdc .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#vchwiftxdc .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#vchwiftxdc .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#vchwiftxdc .gt_left {
  text-align: left;
}

#vchwiftxdc .gt_center {
  text-align: center;
}

#vchwiftxdc .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#vchwiftxdc .gt_font_normal {
  font-weight: normal;
}

#vchwiftxdc .gt_font_bold {
  font-weight: bold;
}

#vchwiftxdc .gt_font_italic {
  font-style: italic;
}

#vchwiftxdc .gt_super {
  font-size: 65%;
}

#vchwiftxdc .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#vchwiftxdc .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#vchwiftxdc .gt_indent_1 {
  text-indent: 5px;
}

#vchwiftxdc .gt_indent_2 {
  text-indent: 10px;
}

#vchwiftxdc .gt_indent_3 {
  text-indent: 15px;
}

#vchwiftxdc .gt_indent_4 {
  text-indent: 20px;
}

#vchwiftxdc .gt_indent_5 {
  text-indent: 25px;
}

#vchwiftxdc .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#vchwiftxdc div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="header gt_col_headings">
<th id="Variable" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Variable</th>
<th id="Definition" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Definition</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">match_id</td>
<td class="gt_row gt_left" headers="Definition">match identification</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">player1</td>
<td class="gt_row gt_left" headers="Definition">first and last name of the first player</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">player2</td>
<td class="gt_row gt_left" headers="Definition">first and last name of the second player</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">elapsed_time</td>
<td class="gt_row gt_left" headers="Definition">time elapsed since start of first point to start of current point (H:MM:SS)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">set_no</td>
<td class="gt_row gt_left" headers="Definition">set number in match</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">game_no</td>
<td class="gt_row gt_left" headers="Definition">game number in set</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">point_no</td>
<td class="gt_row gt_left" headers="Definition">point number in game</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">p1_sets</td>
<td class="gt_row gt_left" headers="Definition">sets won by player 1</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">p1_games</td>
<td class="gt_row gt_left" headers="Definition">games won by player 1 in current set</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">p1_score</td>
<td class="gt_row gt_left" headers="Definition">player 1's score within current game</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">server</td>
<td class="gt_row gt_left" headers="Definition">server of the point</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">serve_no</td>
<td class="gt_row gt_left" headers="Definition">first or second serve</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">point_victor</td>
<td class="gt_row gt_left" headers="Definition">winner of the point</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">p1_points_won</td>
<td class="gt_row gt_left" headers="Definition">number of points won by player 1 in match</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">game_victor</td>
<td class="gt_row gt_left" headers="Definition">a player won a game this point</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">set_victor</td>
<td class="gt_row gt_left" headers="Definition">a player won a set this point</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">p1_ace</td>
<td class="gt_row gt_left" headers="Definition">player 1 hit an untouchable winning serve</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">p1_winner</td>
<td class="gt_row gt_left" headers="Definition">player 1 hit an untouchable winning shot</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">winner_shot_type</td>
<td class="gt_row gt_left" headers="Definition">category of untouchable shot</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">p1_double_fault</td>
<td class="gt_row gt_left" headers="Definition">player 1 missed both serves and lost the point</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">p1_unf_err</td>
<td class="gt_row gt_left" headers="Definition">player 1 made an unforced error</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">p1_net_pt</td>
<td class="gt_row gt_left" headers="Definition">player 1 made it to the net</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">p1_net_pt_won</td>
<td class="gt_row gt_left" headers="Definition">player 1 won the point while at the net</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">p1_break_pt</td>
<td class="gt_row gt_left" headers="Definition">player 1 has an opportunity to win a game player 2 is serving</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">p1_break_pt_won</td>
<td class="gt_row gt_left" headers="Definition">player 1 won the game player 2 is serving</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">p1_break_pt_missed</td>
<td class="gt_row gt_left" headers="Definition">player 1 missed an opportunity to win a game player 2 is serving</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">p1_distance_run</td>
<td class="gt_row gt_left" headers="Definition">player 1's distance ran during point (meters)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">rally_count</td>
<td class="gt_row gt_left" headers="Definition">number of shots during the point</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">speed_mph</td>
<td class="gt_row gt_left" headers="Definition">speed of serve (miles per hour; mph)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">serve_width</td>
<td class="gt_row gt_left" headers="Definition">direction of serve</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">serve_depth</td>
<td class="gt_row gt_left" headers="Definition">depth of serve</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">return_depth</td>
<td class="gt_row gt_left" headers="Definition">depth of return</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
</details></section>
<section id="viewing-your-data" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="viewing-your-data">Viewing your data</h2>
<p>You saw that <code>glimpse()</code> is one way to get a quick look at your data. Often, you’ll want to view your whole dataset. There are two ways to do this:</p>

<div class="no-row-height column-margin column-container"><div class="">
<p><br>
<strong>TIP:</strong> Recall that RStudio is split into four quadrants: Source (upper left), <strong>Environment</strong> (upper right), <strong>Console</strong> (bottom left), and Files/Plots/Packages/Help/Viewer (bottom right)</p>
</div></div><ol type="1">
<li>type <code>View(tennis)</code> in your <strong>Console</strong> and then click return/Enter on your keyboard.</li>
<li>OR, in your <strong>Environment</strong> tab, double click the name of the dataset you want to view.</li>
</ol>
<p>This will open up your data in a new viewer tab so that you can view it like a spreadsheet (like Google Sheets or Excel*). Once open, you can sort the data by clicking on a column.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>*Unlike Google Sheets or Excel, however, you won’t be able to <em>edit</em> the data directly in the spreadsheet.</p>
</div></div><div class="callout callout-style-default callout-note no-icon callout-titled" title="Exercise 1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 1
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>View</code> the <code>tennis</code> data and sort it appropriately to answer the following questions:</p>
<ol type="a">
<li><p>We will be interested in the distances run. Which variables in the data set contain this data? What are example values (and units) for this data? What are the smallest and largest values?</p></li>
<li><p>The second research question involves the percentage of points won on the first serve. What variables provide information related to this question? What type of variables are they and what are the possible values for each?</p></li>
</ol>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p><br>
<strong>TIP:</strong> Type your answers to each exercise in the .qmd document.<br>
<br>
<br>
<br>
<br>
</p>
</div><div class="">
<p><strong>TIP</strong>: When viewing the data, clicking on a column once will sort the data according to that variable in <em>ascending</em> order; clicking twice will sort in <em>descending</em> order.</p>
</div></div>
</section>
</section>
<section id="sample-size-overview" class="level1">
<h1>Sample Size Overview</h1>
<p>We will use statistical hypothesis testing to help address research questions using data (samples). The tests involve the basic hypotheses:</p>
<p><span class="math inline">\(H_0\)</span>: there is no effect/difference, the “status quo” (null hypothesis)</p>
<p><span class="math inline">\(H_a\)</span>: there is an effect/difference (alternative hypothesis)</p>
<p>We are typically hoping to use the data to “reject” the null hypothesis and provide evidence that there is an effect. As a simple example, suppose we develop a new training method to improve serving accuracy in tennis. We will set up an experiment to compare percentage of first serves that are in (accurate) before and after the new training is applied. The hypotheses would be:</p>
<p><span class="math inline">\(H_0\)</span>: there is no difference in first serve percentage before and after the training (null hypothesis)</p>
<p><span class="math inline">\(H_a\)</span>: there is a difference (improvement) in first serve percentage after the training (alternative hypothesis)</p>
<p>The question before the experiment is how many samples should we collect in order to test the hypothesis?</p>
<section id="why-does-sample-size-matter" class="level2">
<h2 class="anchored" data-anchor-id="why-does-sample-size-matter">Why does sample size matter</h2>
<p>There are several things that drive the need for sample size calculations. One is resources. Often it is costly - financially, time, difficulty in getting data - to conduct an experiment so we wish to do so efficiently, with the smallest sample possible. The second is that we want a sample size that will ensure we can get meaningful results from our study. The last thing anyone wants after spending time and money on research is for the results to be inconclusive.</p>
<section id="types-of-errors" class="level3">
<h3 class="anchored" data-anchor-id="types-of-errors">Types of errors</h3>
<p>Two types of errors can occur with a statistical hypotheses test.</p>
<ul>
<li><p><strong>Type I error</strong>: the null hypothesis is true but we reject it.</p></li>
<li><p><strong>Type II error</strong>: the null hypothesis is false but we fail to reject it.</p></li>
</ul>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>The errors are a trade off - if we improve one, the other is worse.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Exercise 2">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 2
</div>
</div>
<div class="callout-body-container callout-body">
<p>For our proposed study of a method to improve first serve perentage:</p>
<ol type="a">
<li><p>What would it mean to have a Type I error?</p></li>
<li><p>What would it mean to have a Type II error?</p></li>
<li><p>Is one error “worse” than the other in this case? Explain.</p></li>
</ol>
</div>
</div>
</section>
<section id="balancing-the-errors" class="level3">
<h3 class="anchored" data-anchor-id="balancing-the-errors">Balancing the errors</h3>
<p>Our goal is to maintain reasonably small chances of both types of errors. The Type I error is typically handled by specifying the probability we make such an error in our hypothesis testing procedure. This probability is usually referred to as <span class="math inline">\(\alpha\)</span> (“alpha”) and set to a low value. Most typically we use <span class="math inline">\(\alpha = 0.05\)</span>. The Type II error, on the other hand, is NOT specified in the testing. This is where sample size can play a role.</p>
<p>Returning to our example, suppose we collect a sample and the first serve percentage without the training is 50% and after the training it is 75%. Using an <span class="math inline">\(\alpha = 0.05\)</span> value, however, we do not reject the null hypothesis. We cannot conclude the sample provides evidence of improvement…even though it seems like a rather positive effect!</p>
<p>Our sample was from two games with 4 first serves each…a very small sample. The problem is that with such a small sample we lack <strong>power</strong> to detect a difference even if it exists. <strong>Power</strong> is defined as:</p>
<p><span class="math display">\[Power = 1 - \beta\]</span> Where <span class="math inline">\(\beta\)</span> is the Type II error rate. Thus, we controlled Type I error but our Type II error rate may be too high!</p>
<p>Small samples lead to large uncertainty about the estimates. Consider the 50% estimate for without training. That was based on 2 of 4 successful serves. However, if only one of the serves had been different (say one more success) that percentage would change by 25%!</p>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>A study that has too small of a sample size to detect a meaningful effect is said to be <strong>under powered</strong>. The Type II error rate is very high.</p>
</div>
</div>
<p>We thus want a sample large enough that it will reject the null hypothesis when there is a true effect. Generally speaking, resource constraints lead to trying to find the smallest sample size that has adequate power to do so. There is little danger of getting “too large” a sample. You might wonder, though, if resources permit why not just get a super large sample. That would give very high power!</p>
<p>The problem with a very large sample is that there is power to detect very, very small effects. For example, suppose we get a sample of millions of serves. The result is 50% success without the training and 50.1% with the training. The gigantic sample could lead to rejecting the null hypothesis, thus concluding there is evidence of difference due to the training.</p>
<p>The sample size gives us great precision in these estimates…and, after, all technically they are different. However, clearly the effect is not really a difference that any tennis play would care about enough to hire you as their trainer.</p>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>A study that has too large of a sample size to detect a meaningful effect is said to be <strong>over powered</strong>. The Type II error rate is so low that meaningless effects are said to be significant.</p>
</div>
</div>
</section>
</section>
<section id="factors-impacting-sample-size-power" class="level2">
<h2 class="anchored" data-anchor-id="factors-impacting-sample-size-power">Factors impacting sample size (power)</h2>
<p>In order to determine the sample size that gets us into the “sweet spot” (not in the sense of hitting a tennis ball) there are four factors that are important in some form for all “power” calculations:</p>
<ol type="1">
<li>The <strong>sample size</strong> (or <strong>power</strong>)</li>
</ol>
<ul>
<li>note that sometimes we use the <strong>power</strong> and compute sample size, and sometimes the reverse. If <strong>power</strong> is used typical choices are <span class="math inline">\(0.8\)</span> or <span class="math inline">\(0.9\)</span> (meaning <span class="math inline">\(\beta = 0.2\)</span> or <span class="math inline">\(\beta = 0.1\)</span> Type II error rates).</li>
</ul>
<ol start="2" type="1">
<li>Your chosen <strong>Type I error rate</strong></li>
</ol>
<ul>
<li>Typically we use <span class="math inline">\(\alpha = 0.05\)</span>.</li>
</ul>
<ol start="3" type="1">
<li>The amount of <strong>variability</strong> in the data.</li>
</ol>
<ul>
<li>Variability impacts the precision of estimates.</li>
</ul>
<ol start="4" type="1">
<li>How <strong>big of a difference</strong> (or <strong>how strong of an association</strong>) you believe exists and is meaningful.</li>
</ol>
<p>Items 3 and 4 must be estimated in some fashion which is often a challenge for sample size calculation. They are often combined and referred to as an <strong>“effect size”</strong>. There are various measures of effect size in different settings with rules of thumb for what constitues small, medium, etc. effect sizes that are then used to compute the desired sample size.</p>
</section>
</section>
<section id="example-1-power-for-two-sample-t-test" class="level1 page-columns page-full">
<h1>Example 1: Power for two sample t-test</h1>
<p>Remember our first research question:</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled" title="Research question">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Research question
</div>
</div>
<div class="callout-body-container callout-body">
<p>What sample size is required for a study of the differences in running distances for tennis players on clay and grass courts</p>
</div>
</div>
<p>We have data for distances run in meters. Our sample will involve those distances on clay and grass courts. The distances are a continuous variable so an appropiate test is two-sample t test. The hypotheses for this test are:</p>
<p><span class="math display">\[H_0: \mu_{clay} = \mu_{grass}\]</span></p>
<p><span class="math display">\[H_a: \mu_{clay} &gt; \mu_{grass}\]</span></p>
<p>where <span class="math inline">\(\mu_{clay}\)</span> is the true average distance run (in meters per point) on clay courts (and similar for <span class="math inline">\(\mu_{grass}\)</span>).</p>
<p><em>Note we used “greater than” in the alternative hypothesis implying we believe the amount of running is greater on clay courts. This reflects the general belief that the “slower court” leads to longer points as players are able to reach the ball more easily even if it is hit further from them.</em></p>
<section id="estimating-the-parameters" class="level2">
<h2 class="anchored" data-anchor-id="estimating-the-parameters">Estimating the Parameters</h2>
<p>With the statistical method defined we are then ready to determine the parameter values we will use to perform our sample size computations. We will compute sample size for a desired power, and set the first two parameters to typical values:</p>
<ol type="1">
<li><p><strong>Power</strong> = <span class="math inline">\(0.8\)</span></p></li>
<li><p><span class="math inline">\(\alpha = 0.05\)</span></p></li>
</ol>
<p>The variability is often estimated from pilot or previous data, or using information from previous studies. We will use our Wimbledon 2023 data. We can compute the standard deviations (sd) for player one run distances and also for player two run distances:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(tennis<span class="sc">$</span>p1_distance_run)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13.49286</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(tennis<span class="sc">$</span>p2_distance_run)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13.60765</code></pre>
</div>
</div>
<p>Both are similar and around 13.5 meters/point. So, we will choose this value:</p>
<ol start="3" type="1">
<li>sd = 13.5 meters/point (estimated variability)</li>
</ol>
<p>The final value we need is the value of the difference in run distance that we would consider meaningful. The mean values for the run distances in the Wimbledon data are:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(tennis<span class="sc">$</span>p1_distance_run)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 14.00231</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(tennis<span class="sc">$</span>p2_distance_run)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13.86924</code></pre>
</div>
</div>
<p>Both are around 14 meters/point. What would represent a meaningful increase for the distance run on clay?</p>
<p>One tool that could help is to consider <strong>effect size</strong>. Cohen (1988) offers some advice. A metric known as Cohen’s D is one measure and is defined:</p>
<p><span class="math display">\[D = \frac{\mu_2 - \mu_1}{sd}\]</span> where the sd is of the difference in means. If the average distance on clay increases by one standard deviation, then <span class="math inline">\(D = 1\)</span>. In other words, Cohen’s D is the increase in terms of the standard deviation. If <span class="math inline">\(D = 0.5\)</span> that would be an increase of half of a standard deviation,</p>
<p>An increase of 1 standard deviation (13.5 meters/point) seems large as it would nearly double the average run per point.</p>
<p>The R package “effectsize” contains a function to provide an interpretation of Cohen’s D values. We provide interpretation for the one standard deviation increase (13.5 meters/point) and for smaller increases of 0.5 and 0.25 standard deviations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">interpret_cohens_d</span>(<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "large"
(Rules: cohen1988)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">interpret_cohens_d</span>(<span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "medium"
(Rules: cohen1988)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">interpret_cohens_d</span>(<span class="fl">0.25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "small"
(Rules: cohen1988)</code></pre>
</div>
</div>
<p>We will opt for a “medium” effect size using the <span class="math inline">\(D = 0.5\)</span> value. That would be an increase of one half of a standard deviation: <span class="math inline">\(0.5 \times 13.5 = 6.75\)</span>.</p>
<ol start="4" type="1">
<li><strong>Difference in means (delta) = 6.75</strong>.</li>
</ol>
</section>
<section id="computing-the-sample-size" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="computing-the-sample-size">Computing the Sample Size</h2>
<p>The R command “power.t.test” computes the sample size (or power). We compute sample size by leaving the parameter “n” as “NULL” (<em>note that NULL is the default so we did not need to explicitly specify in running the commmand</em>). We must specify the power in this case; alternatively we could give a value of “n” and make the power NULL to compute power.</p>
<p>Other values are shown below.</p>
<p><em>Note that the type is “two.sample” because we are comparing two sample means.</em></p>
<p><em>The alternative is “one.sided” because we hypothesized and increase (&gt;) in distance run on clay courts. A <span class="math inline">\(\ne\)</span> alternative hypothesis would be “two.sided”.</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">power.t.test</span>(<span class="at">n =</span> <span class="cn">NULL</span>, </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">delta =</span> <span class="fl">6.76</span>, </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">sd =</span> <span class="fl">13.5</span>, </span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">sig.level =</span> <span class="fl">0.05</span>,</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">power =</span> <span class="fl">0.8</span>,</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">type =</span> <span class="fu">c</span>(<span class="st">"two.sample"</span>),</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">alternative =</span> <span class="fu">c</span>(<span class="st">"one.sided"</span>)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>             )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Two-sample t test power calculation 

              n = 50.00462
          delta = 6.76
             sd = 13.5
      sig.level = 0.05
          power = 0.8
    alternative = one.sided

NOTE: n is number in *each* group</code></pre>
</div>
</div>
<p>The value returned is <strong>n = 50.00462</strong> which is the number per group (so points observed on each of the two court surfaces). We <strong>always round up</strong> to ensure adequate power so we will need <strong>n = 51 points per court surface</strong> to conduct our study.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Exercise 3">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 3
</div>
</div>
<div class="callout-body-container callout-body">
<p>In the next exercises, we will examine how various parameters impact the required sample size. Let’s look first at the impact of <strong>power</strong>.</p>
<ol type="a">
<li><p>Rerun the sample size calculation increasing the desired power to 0.9. What sample size is required?</p></li>
<li><p>Rerun the sample size calculation decreasing the desired power to 0.7. What sample size is required?</p></li>
<li><p>Does increasing the power impact the required sample size? Why?</p></li>
</ol>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p><strong>TIP</strong>: copy the command in our example and change the parameters as needed to complete each exercise.</p>
</div></div><div class="callout callout-style-default callout-note no-icon callout-titled" title="Exercise 4">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 4
</div>
</div>
<div class="callout-body-container callout-body">
<p>Impact of <strong>(alpha)</strong>. Return to a power of 0.8 for this exercise.</p>
<ol type="a">
<li><p>Rerun the sample size calculation decreasing the desired alpha to 0.01. What sample size is required?</p></li>
<li><p>Rerun the sample size calculation increasing the desired alpha to 0.1. What sample size is required?</p></li>
<li><p>How does changing the allowable Type I error impact the required sample size? Why?</p></li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Exercise 5">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 5
</div>
</div>
<div class="callout-body-container callout-body">
<p>Impact of variability, <strong>sd</strong>. Return to a power of 0.8 and alpha of 0.05</p>
<ol type="a">
<li><p>Increase the sd to 15. What sample size is required?</p></li>
<li><p>Increase the sd to 10. What sample size is required?</p></li>
<li><p>How does the estimated variability in the data impact the required sample size? Why?</p></li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Exercise 6">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 6
</div>
</div>
<div class="callout-body-container callout-body">
<p>Impact of size of the difference, <strong>delta</strong>. Return to a power of 0.8, alpha of 0.05, and sd of 13.5.</p>
<ol type="a">
<li><p>What value of delta leads to a small effect of D = 0.25 standard deviation increase?</p></li>
<li><p>What value of delta produces a large effect of D = 1 sd increase?</p></li>
<li><p>Find the sample size for the delta values computed in a and b.</p></li>
<li><p>How does the effect size impact the required sample size? Why?</p></li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Exercise 7">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 7
</div>
</div>
<div class="callout-body-container callout-body">
<p>Computing <strong>power</strong> instead of sample size. Use the original values in the example (delta = 6.75, sd = 13.5, alpha = 0.05). We computed a sample size of 51 to achieve power of 0.8 in the example.</p>
<ol type="a">
<li><p>Modify the command by setting power to “NULL” and the sample size to n = 51. Does the computed power exceed 0.8?</p></li>
<li><p>What is the power if n = 50 (recall we rounded up)?</p></li>
</ol>
</div>
</div>
</section>
</section>
<section id="example-2-power-for-two-sample-test-of-proportions" class="level1">
<h1>Example 2: Power for two sample test of proportions</h1>
<p>Now let’s consider our second research question:</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled" title="Research question">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Research question
</div>
</div>
<div class="callout-body-container callout-body">
<p>What sample size is required for a study of the differences in percentage of points won on the first serve for tennis players on clay and grass courts?</p>
</div>
</div>
<p>We are now considering comparison of proportions (of points won when hitting a first serve into the court). Our sample will involve those proportions on clay and grass courts. The appropiate test is thus the two-sample test of proportions. The hypotheses for this test are:</p>
<p><span class="math display">\[H_0: p_{clay} = p_{grass}\]</span> <span class="math display">\[H_a: p_{clay} &lt; p_{grass}\]</span></p>
<p>where p is the true proportion of first serve points won on the given surface.</p>
<p>Notice that we again chose a one sided alternative, but this time with the proportion on clay courts less than on grass. The slower clay courts are thought to make it easier to return hard first serves. Again, if we did not have prior knowledge about the impact of the surface we would use a <span class="math inline">\(\ne\)</span> alternative here.</p>
<section id="estimating-the-parameters-1" class="level2">
<h2 class="anchored" data-anchor-id="estimating-the-parameters-1">Estimating the Parameters</h2>
<p>We will again compute sample size for a desired power, and set the first two parameters to typical values:</p>
<ol type="1">
<li><p><strong>Power</strong> = <span class="math inline">\(0.8\)</span></p></li>
<li><p><span class="math inline">\(\alpha = 0.05\)</span></p></li>
</ol>
<p>The third parameter, estimate of variability, is not needed for the two sample proportions test. The reason is that the variance for a proportion is actually a function of the proportion. This comes from the variance for a binary (0 or 1) variable which is modeled using the Binomial (Bernoulli) distribution. If the true proportion is p, then the variance is:</p>
<p><span class="math display">\[p \times (1-p)\]</span></p>
<p>So, once we provide a hypothesized value for p, then the variance can be computed!</p>
<p>The fourth parameter is again the difference we would consider meaningful. We can use our data to get an estimate for the proportion of points won on grass for a first serve.</p>
<p>We first get the percentage for player one. The “filter” function allows us to select only first serve data (“serve_no ==1”) when player one is serving (“server == 1”). We then obtain the table with percentages of which player won the point.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>p1serve1 <span class="ot">&lt;-</span> tennis <span class="sc">|&gt;</span> <span class="fu">filter</span>(serve_no <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> server <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">PercTable</span>(p1serve1<span class="sc">$</span>point_victor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               
    freq   perc
               
1  1'728  76.6%
2    529  23.4%</code></pre>
</div>
</div>
<p>Since player 1 is the server in this reduced data set, we see that the server wins 76.6% of the points.</p>
<p>We can repeat this for player two (below) and find a similar percentage of 74.3%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>p2serve1 <span class="ot">&lt;-</span> tennis <span class="sc">|&gt;</span> <span class="fu">filter</span>(serve_no <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> server <span class="sc">==</span> <span class="dv">2</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">PercTable</span>(p2serve1<span class="sc">$</span>point_victor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               
    freq   perc
               
1    616  25.7%
2  1'784  74.3%</code></pre>
</div>
</div>
<p>We select a reasonable percentage then for Wimbledon (grass) of 75%. The question is what would be a noteworthy difference in winning percentage on clay.</p>
<p>We can again consider effect size, and R package “pwr” provides a function “ES.h” that computes an effect size based on two proportions known as Cohen’s H (Cohen, 1988). The rules of thumb for this value are the same as for Cohen’s D, so we can again use the “interpret_cohens_d” function once we obtain a value.</p>
<p>Let’s see what the effect size is if the percentage won on clay is only 50%:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>prop_effect <span class="ot">&lt;-</span> <span class="fu">ES.h</span>(<span class="fl">0.75</span>, <span class="fl">0.5</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>prop_effect</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5235988</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">interpret_cohens_d</span>(prop_effect)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "medium"
(Rules: cohen1988)</code></pre>
</div>
</div>
<p>The result is a “medium” effect, but practically that seems like an unlikely change. Even though clay might reduce the serve advantage, it still probably exists. Let’s consider reducing the advantage to 65%:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>prop_effect <span class="ot">&lt;-</span> <span class="fu">ES.h</span>(<span class="fl">0.75</span>, <span class="fl">0.65</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>prop_effect</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2189061</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">interpret_cohens_d</span>(prop_effect)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "small"
(Rules: cohen1988)</code></pre>
</div>
</div>
<p>This is a small effect size, but practically certainly meaningful so we will use this in our calculations:</p>
<ol start="4" type="1">
<li><strong>Difference in proportions</strong>: 0.1 (from 0.75 to 0.65)</li>
</ol>
</section>
<section id="computing-the-sample-size-1" class="level2">
<h2 class="anchored" data-anchor-id="computing-the-sample-size-1">Computing the Sample Size</h2>
<p>The command for proportions is “power.prop.test”. For difference in proportions, we actually input the two proportions rather than the delta. As we will see in the exercises, this matters as the estimate of the variance is based on the hypothesized proportion. The rest of the options are similar to those for the two sample t-test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">power.prop.test</span>(<span class="at">n =</span> <span class="cn">NULL</span>, </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">p1 =</span> <span class="fl">0.75</span>, </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">p2 =</span> <span class="fl">0.65</span>, </span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">sig.level =</span> <span class="fl">0.05</span>, </span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">power =</span> <span class="fl">0.8</span>,</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">alternative =</span> <span class="st">"one.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Two-sample comparison of proportions power calculation 

              n = 258.619
             p1 = 0.75
             p2 = 0.65
      sig.level = 0.05
          power = 0.8
    alternative = one.sided

NOTE: n is number in *each* group</code></pre>
</div>
</div>
<p>The value returned is <strong>n = 258.619</strong> per group so we will need <strong>n = 259 points per court surface</strong> to conduct this second study.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Exercise 8">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 8
</div>
</div>
<div class="callout-body-container callout-body">
<p>As mentioned in the example, the hypothesized proportion impacts the estimate of the variance. We explore this impact in this exercise.</p>
<ol type="a">
<li><p>Modify the sample size calculation so that the effect is still 0.1 but based on 70% for p1 and 60% for p2. What is the resulting sample size? How does this compare to the sample size in the example using 75% and 60%?</p></li>
<li><p>The variance estimate is related to the value <span class="math inline">\(p \times (1-p)\)</span>. What is this value if p = 0.75? What is the value when p = 0.7? Which variance is larger?</p></li>
<li><p>Based on the results from part b, and from your exploration of the role of variability in sample size calculations for the two sample t-test, explain the change in sample size in part a.</p></li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Exercise 9">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 9
</div>
</div>
<div class="callout-body-container callout-body">
<p>Formulate an additional question that involves two sample means using variables available in the data set and compute sample size in similar fashion to example 1.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Exercise 10">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 10
</div>
</div>
<div class="callout-body-container callout-body">
<p>Formulate an additional question that involves two sample proportions using variables available in the data set and compute sample size in similar fashion to example 2.</p>
</div>
</div>
</section>
</section>
<section id="references" class="level1">
<h1>REFERENCES</h1>
<p>Cohen, J. (1988). Statistical power analysis for the behavioral sciences (2nd Ed.). New York: Routledge.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Maintained by Katie Fitzgerald <br> We use cookies to track usage statistics to help measure impact of the materials for authors. Please consider allowing tracking cookies.</p>
<div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Manage cookies</a></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>