{
  "hash": "6bef45aff153b5451c81e91198e72b5c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"MMA Fight Decisions\"\nauthor:\n  - name: Rodney X. Sturdivant, Ph.D.\n    email: Rodney_Sturdivant@baylor.edu\n    affiliation:\n      - id: baylor\n        name: Baylor University\n  - name: Ian Young\n    affiliation:\n      - ref: baylor\n  - name: Joshua Patrick, Ph.D.\n    affiliation:\n      - ref: baylor\n  - name: Connor Bryson\n    affiliation:\n      - ref: baylor\ndate: July 1, 2024\nformat:\n  html:\n    embed-resources: true\n    self-contained-math: true\n    grid:\n      margin-width: 350px\ntoc: true\ntoc-location: left\ndescription: Exploring MMA fight decisions by weight category\ncategories:\n  - Variable types\n  - Chi-square test (2x2)\n  - Fisher Exact test\n  - Chi-square test (rxc)\n  - Mosaic plots\neditor_options:\n  chunk_output_type: console\ncallout-icon: false\n---\n\n\n::: {.callout-note collapse=\"true\" title=\"Facilitation notes\" appearance=\"minimal\"}\n+ This module would be suitable for an in-class lab or take-home assignment in an introductory statistics course. \n\n+ It assumes a basic familiarity with the RStudio Environment has already been covered, but no prior programming experiences is expected.\n\n+ Students should be provided with the following data file (.csv) and Quarto document (.qmd) to produce tests/visualizations and write up their answers to each exercise. Their final deliverable is to turn in an .html document produced by \"Rendering\" the .qmd. \n  \n  + [data](mma.csv)\n  + [Student Quarto template](mma_student_template.qmd)\n\n+ [Posit Cloud](https://posit.cloud/) (via an Instructor account) or [Github classroom](https://classroom.github.com) are good options for disseminating files to students, but simply uploading files to your university's course management system works, too.\n:::\n\n# Welcome video\n\n<iframe width=\"560\" height=\"315\" src title=\"placeholder\">\n\n</iframe>\n\n# Introduction\n\nIn this module, you will be analyzing data from mixed marshall arts (MMA) fights in order to determine if the weight class of the fighters is related to the type of decision that ended the fight.  \n\n::: {.callout-note title=\"Learning Objectives\" appearance=\"minimal\"}\nBy the end of this module, you will be able to:\n\n-   Read (import) a dataset into your RStudio Environment\n\n-   Use R to visualize the following types of variables:\n\n    -   two categorical variable (mosaic and plots)\n\n-   Test for an association between two categorical variables (2 categories each)\n\n    - Using the Chi-square test\n    \n    - Using Fisher's Exact test\n    \n-   Test for an association between two categorical variables (more than 2 categories each)\n   \n:::\n\n::: column-margin\n\\\n\\\n\\\n\\\n\n**NOTE**: **R** is the name of the programming language itself and **RStudio** is a convenient interface. To throw even more lingo in, you may be accessing RStudio through a web-based version called **Posit Cloud**. But R is the programming language you are learning :) \n:::\n\n::: {.callout-caution collapse=\"true\" title=\"Research Questions\"}\n\nDuring this lab, you'll investigate the following research questions (don't worry if you're new to MMA, we'll introduce lingo soon!):\n\n+ What are the percentages of MMA fight decisions for different weight classes?\n+ Are percentages in decisions different based on weight class?\n\n:::\n\n# Getting started: MMA data\n\nThe first step to any analysis in R is to **load necessary packages and data**. \n\n::: column-margin\nYou can think of **packages** like apps on your phone; they extend the functionality and give you access to many more features beyond what comes in the “base package”.\n:::\n\nRunning the following code will load the `tidyverse`, `ggplot2`, other packages, and the `mma` data we will be using in this lab.\n\n\n\n::: column-margin\n**TIP**: As you follow along in the lab, you should run each corresponding code chunk in your .qmd document. To \"Run\" a code chunk, you can press the green \"Play\" button in the top right corner of the code chunk in your .qmd. You can also place your cursor anywhere in the line(s) of code you want to run and press \"command + return\" (Mac) or \"Ctrl + Enter\" (Windows).\n:::\n\n::: column-margin\n**TIP**: Using a hashtag in R allows you to add comments to your code (in plain English). Data scientists often use comments to explain what each piece of the code is doing.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse) #loads package\nlibrary(ggplot2)\nlibrary(DescTools)\n\nmma <- read_csv(\"mma.csv\") #loads data\n```\n:::\n\n\nWe can use the `glimpse()` function to get a quick look (errr.. glimpse) at our `mma` data. The `glimpse` code provides the number of observations (Rows) and the number of variables (Columns) in the dataset. The “Rows” and “Columns” are referred to as the **dimensions** of the dataset. It also shows us the names of the variables (`date`, `day`, ..., `wtClass`) and the first few observations for each variable (e.g. the first two fights in the dataset took place on December 4, 2010 and May 15, 2010).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(mma)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 28,771\nColumns: 20\n$ date           <chr> \"12/4/10\", \"5/15/10\", \"6/12/09\", \"1/23/09\", \"3/25/22\", …\n$ month          <dbl> 12, 5, 6, 1, 3, 4, 2, 5, 1, 9, 1, 8, 6, 12, 2, 3, 1, 12…\n$ year           <dbl> 2010, 2010, 2009, 2009, 2022, 2021, 2021, 2018, 2018, 2…\n$ event          <chr> \"Strikeforce: Henderson vs. Babalu 2\", \"Strikeforce: He…\n$ championship   <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,…\n$ decision       <chr> \"Decision - Unanimous\", \"Submission\", \"TKO\", \"Unanimous…\n$ decision_group <chr> \"Decision\", \"Submission\", \"KO/TKO\", \"Decision\", \"KO/TKO…\n$ round          <chr> \"3\", \"1\", \"2\", \"3\", \"1\", \"3\", \"3\", \"2\", \"1\", \"3\", \"1\", …\n$ time           <time> 05:00:00, 00:56:00, 01:47:00, 05:00:00, 01:37:00, 05:0…\n$ p1_result      <chr> \"L\", \"W\", \"L\", \"L\", \"L\", \"L\", \"W\", \"L\", \"L\", \"W\", \"L\", …\n$ p1_id          <dbl> 2504991, 2504991, 2504991, 2504991, 4239497, 4239497, 4…\n$ p1_name        <chr> \"Aaron, Tom\", \"Aaron, Tom\", \"Aaron, Tom\", \"Aaron, Tom\",…\n$ p1_country     <chr> \"USA\", \"USA\", \"USA\", \"USA\", \"ESP\", \"ESP\", \"ESP\", \"ESP\",…\n$ p1_sex         <chr> \"M\", \"M\", \"M\", \"M\", \"M\", \"M\", \"M\", \"M\", \"M\", \"M\", \"M\", …\n$ p2_result      <chr> \"W\", \"L\", \"W\", \"W\", \"W\", \"W\", \"L\", \"W\", \"W\", \"L\", \"W\", …\n$ p2_id          <dbl> 2504993, 2504992, 2504956, 2514253, 5078428, 4236955, 4…\n$ p2_name        <chr> \"Ricehouse, Matt\", \"Steenberg, Eric\", \"Voelker, Bobby\",…\n$ p2_country     <chr> \"USA\", \"CAN\", \"USA\", \"USA\", \"BRA\", \"USA\", \"ENG\", \"USA\",…\n$ p2_sex         <chr> \"M\", \"M\", \"M\", \"M\", \"M\", \"M\", \"M\", \"M\", \"M\", \"M\", \"M\", …\n$ wtClass        <chr> \"Lightweight\", \"Catchweight\", \"Welterweight\", \"Lightwei…\n```\n\n\n:::\n:::\n\n\n::: column-margin\n**ERROR?** Did you get a error message that says `could not find function \"glimpse\"`? This means you need to load the `tidyverse` package. You can do this by running the code `library(tidyverse)` from the previous code chunk. A shortcut is to hit the \"fast-forward\" button (next to the \"Play\" button in your code chunk), which will run all code chunks above your current one.\n:::\n\n\n::: {.callout-note  title=\"Exercise 1\"}\n\na. What are the **dimensions** of this dataset?\n\n\nb. What are the **observational units** for this data? That is, what does one row represent?\n\nc. How many **categorical variables** are there? List the names of these variables.  \n\nd. How many **ordinal variables** are there? List the names of these variables.  Note that the tests we will introduce in the module are only appropriate for categorical (or possibly ordinal) variables!\n\n:::\n\n::: column-margin\n\\\n**TIP:** Type your answers to each exercise in the .qmd document. \n\\\n\\\n\\\n\\\n**TIP:** To determine if a variable is categorical, read more about variable types [here](https://stats.oarc.ucla.edu/other/mult-pkg/whatstat/what-is-the-difference-between-categorical-ordinal-and-interval-variables/).\n:::\n\n## MMA lingo\n\nBefore proceeding with any analysis, let's make sure we know some MMA lingo in order to understand what information is contained in each variable (column) in our dataset.\n\n\n#### The basics\n-   Fighters are in different **weight classes** and may only fight in their own class or higher weight classes.\n    - There are 8 classes for men and 4 for women.\n-   Fights consist of rounds (typically 3).\n-   Fights may end early due to:\n    - A **submission**: one fighter \"taps out\" or concedes.\n    - **Knock out (KO)** or **Technical knock out (TKO)** (the referee stops the fight).\n- If a fight is not stopped early, then the winner is determined by judges (known as a **decision**).\n    - The decision could be unanimous (U) if all judges agree, or split (S) if not all judges agree.\n-   **Championship fights** are those which determine who is the champion of a given weight class.\n\n\n::: column-margin\nTotally new to MMA? See this site: [INTRODUCTION TO MMA](https://www.ufc.com/intro-to-mma?language_content_entity=en)\n:::\n\n::: {.callout-important}\n\n#### Weight Classes in the mma data set\n\n-   Currently there are 12 [UFC weight classes](https://www.ufc.com/news/understanding-ufc-weight-classes-and-weigh-ins?language_content_entity=en).  From lightest to heaviest:\n    - Strawweight\t115 lb, Flyweight\t125 lb, Bantamweight 135 lb, \n    Featherweight\t145 lb, Lightweight\t155 lb, Super lightweight\t165 lb,\n    Welterweight\t170 lb, Super welterweight\t175 lb, Middleweight\t185 lb,\n    Super middleweight\t195 lb, Light heavyweight\t205 lb, \n    Cruiserweight\t225 lb, Heavyweight\t265 lb, Super heavyweight\t\n-   Our mma data set includes fights from only 9 of the 12 classes. \n-   The original data listed both fighter weight classes\n    - For some fights the fighters were from different weight classes\n    - We assumed the fight weight class was the heavier class of the two fighters.\n-   Three additional weight classes are listed in the data: \n    - **Atomweight**: a class recognized by some fight organizations for women that is lighter (105 lbs) than the 12 classes.\n    - **Catchweight**: fights that don't follow traditional weight classes, often agree to in contracts between fighters.\n    - **Open Weight**: unofficial weight class that allow fighters of different sizes to compete against each other with no weight limit.\n\n:::\n\n\n## Variable descriptions\n\nThe data used for the following examples is MMA fight data. The data is a SAMPLE of fights from 1991 to 2023 (not all fights in that period). In addition to data about the fight generally (date, name of event, whether it was a \"championship\" fight etc) data is provided for each fighter participating in the fight (columns starting with p1 are the first fighter and p2 the second). \n\n<details>\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"xjkourrqdo\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#xjkourrqdo table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#xjkourrqdo thead, #xjkourrqdo tbody, #xjkourrqdo tfoot, #xjkourrqdo tr, #xjkourrqdo td, #xjkourrqdo th {\n  border-style: none;\n}\n\n#xjkourrqdo p {\n  margin: 0;\n  padding: 0;\n}\n\n#xjkourrqdo .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xjkourrqdo .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#xjkourrqdo .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xjkourrqdo .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xjkourrqdo .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xjkourrqdo .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xjkourrqdo .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xjkourrqdo .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xjkourrqdo .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xjkourrqdo .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xjkourrqdo .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xjkourrqdo .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xjkourrqdo .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#xjkourrqdo .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#xjkourrqdo .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xjkourrqdo .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xjkourrqdo .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xjkourrqdo .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xjkourrqdo .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xjkourrqdo .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xjkourrqdo .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xjkourrqdo .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#xjkourrqdo .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xjkourrqdo .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xjkourrqdo .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xjkourrqdo .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xjkourrqdo .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xjkourrqdo .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xjkourrqdo .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xjkourrqdo .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xjkourrqdo .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xjkourrqdo .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xjkourrqdo .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xjkourrqdo .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xjkourrqdo .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xjkourrqdo .gt_left {\n  text-align: left;\n}\n\n#xjkourrqdo .gt_center {\n  text-align: center;\n}\n\n#xjkourrqdo .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xjkourrqdo .gt_font_normal {\n  font-weight: normal;\n}\n\n#xjkourrqdo .gt_font_bold {\n  font-weight: bold;\n}\n\n#xjkourrqdo .gt_font_italic {\n  font-style: italic;\n}\n\n#xjkourrqdo .gt_super {\n  font-size: 65%;\n}\n\n#xjkourrqdo .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#xjkourrqdo .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xjkourrqdo .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#xjkourrqdo .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#xjkourrqdo .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#xjkourrqdo .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#xjkourrqdo .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Variable\">Variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Definition\">Definition</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Example_Values\">Example_Values</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">date</td>\n<td headers=\"Definition\" class=\"gt_row gt_left\">date of the event (mdy)</td>\n<td headers=\"Example_Values\" class=\"gt_row gt_left\">10/12/2023</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">month</td>\n<td headers=\"Definition\" class=\"gt_row gt_left\">month of the event</td>\n<td headers=\"Example_Values\" class=\"gt_row gt_left\">10</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">year</td>\n<td headers=\"Definition\" class=\"gt_row gt_left\">year of the event</td>\n<td headers=\"Example_Values\" class=\"gt_row gt_left\">2023</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">event</td>\n<td headers=\"Definition\" class=\"gt_row gt_left\">name of the event</td>\n<td headers=\"Example_Values\" class=\"gt_row gt_left\">UFC 1: The Beginning</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">championship</td>\n<td headers=\"Definition\" class=\"gt_row gt_left\">is the event a championship event</td>\n<td headers=\"Example_Values\" class=\"gt_row gt_left\">TRUE/FALSE</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">decision</td>\n<td headers=\"Definition\" class=\"gt_row gt_left\">fight result</td>\n<td headers=\"Example_Values\" class=\"gt_row gt_left\">TKO (Injury)</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">decision_group</td>\n<td headers=\"Definition\" class=\"gt_row gt_left\">aggregated groups of decision variable</td>\n<td headers=\"Example_Values\" class=\"gt_row gt_left\">KO/TKO</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">round</td>\n<td headers=\"Definition\" class=\"gt_row gt_left\">how many rounds the fight lasted</td>\n<td headers=\"Example_Values\" class=\"gt_row gt_left\">3</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">time</td>\n<td headers=\"Definition\" class=\"gt_row gt_left\">time the fight ended</td>\n<td headers=\"Example_Values\" class=\"gt_row gt_left\">4:42</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">p1_result</td>\n<td headers=\"Definition\" class=\"gt_row gt_left\">result of the fight for fighter 1(2)</td>\n<td headers=\"Example_Values\" class=\"gt_row gt_left\">W</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">p1_id</td>\n<td headers=\"Definition\" class=\"gt_row gt_left\">a unique ID for fighter 1(2)</td>\n<td headers=\"Example_Values\" class=\"gt_row gt_left\">2354059</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">p1_name</td>\n<td headers=\"Definition\" class=\"gt_row gt_left\">full name of fighter 1(2)</td>\n<td headers=\"Example_Values\" class=\"gt_row gt_left\">Shamrock, Ken</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">p1_country</td>\n<td headers=\"Definition\" class=\"gt_row gt_left\">home country of fighter 1(2)</td>\n<td headers=\"Example_Values\" class=\"gt_row gt_left\">USA</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">p1_sex</td>\n<td headers=\"Definition\" class=\"gt_row gt_left\">sex of fighter 1(2)</td>\n<td headers=\"Example_Values\" class=\"gt_row gt_left\">M</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">wtClass</td>\n<td headers=\"Definition\" class=\"gt_row gt_left\">aggregated groups of Weight Class</td>\n<td headers=\"Example_Values\" class=\"gt_row gt_left\">Heavyweight</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Viewing your data\n\nYou saw that `glimpse()` is one way to get a quick look at your data. Often, you'll want to view your whole dataset. There are two ways to do this:\n\n::: column-margin :::\n\\\n**TIP:** Recall that RStudio is split into four quadrants: Source (upper left), **Environment** (upper right), **Console** (bottom left), and Files/Plots/Packages/Help/Viewer (bottom right)\n\n:::\n\n1. type `View(mma)` in your **Console** and then click return/Enter on your keyboard. \n2. OR, in your **Environment** tab, double click the name of the dataset you want to view. \n\nThis will open up your data in a new viewer tab so that you can view it like a spreadsheet (like Google Sheets or Excel\\*). Once open, you can sort the data by clicking on a column. \n\n::: column-margin :::\n\\*Unlike Google Sheets or Excel, however, you won't be able to *edit* the data directly in the spreadsheet.\n:::\n\n::: {.callout-note  title=\"Exercise 2\"}\n\n`View` the `mma` data and sort it appropriately to answer the following questions:\n\na. What was the latest fight date in the data set?\n\nb. What was the event of the fight(s) on this date?\n\nc. How many fights took place at this event?\n\nd. How many of these fights ended with a KO or TKO?\n\ne. Which fighters one the fights ending in KO or TKO?\n\nf. What weight class were the fighters who won by KO or TKO?\n\n:::\n\n::: column-margin :::\n**TIP**: When viewing the data, clicking on a column once will sort the data according to that variable in *ascending* order; clicking twice will sort in *descending* order.\n:::\n\n# Chi-square Test Overview\n\nThe chi-square test is a test used to determine if there is a significant association between two categorical variables. It compares the observed frequencies of the different categories with the expected independent frequencies. The hypotheses involved are:\n\n- $H_0:$  there is no assocation between the two variables (null hypothesis)\n- $H_a:$  there is an assocation between the two variables (alternative hypothesis)\n\nWe will use the MMA data to explore the test and determine if, since the year 2020, fighter weight class and the decision of a fight are associated. In order to perform the analyis we will produce a \"contingency table\" displaying the data (*note: To perform a chi-square test in many software packages, it is often not necessary to format the data into a contingency table. Many packages can take data from a standard rectangular data table and pass it through a chi-square function.*). Additionally, we will illustrate how to present the data in a more visual format.  \n\n\n# Chi-square Test Example\n\n::: {.callout-caution title=\"Research question\"}\n\nIs there difference in the proportion of fights ending in a decision between the heavyweight and middleweight classes since 2020?\n\n:::\n\n## Preparing the data\n\nWe first select the variables of interest, and \"filter\" the data to the categories we wish to compare and the years of interest.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Select, filter, and prepare relevant data for analysis\ndata1 <- mma |> \n  select(year, wtClass, decision_group) |> \n  filter(year >= 2020) |>\n  filter(wtClass == \"Middleweight\" | wtClass == \"Heavyweight\") |> \n  mutate(decision = if_else(decision_group == \"Decision\", \"Decision\",\n                            \"KO/TKO/Submission\"))\n```\n:::\n\n\n::: column-margin :::\n**TIP**: in logical expressions, a double equal sign is used \"==\". \n:::\n\n::: column-margin :::\n**TIP**: in logical expressions, \"|\" is \"OR\" \n:::\n\n::: column-margin :::\n**TIP**: mutate is a dplyr function that allows us to create new variables. \n:::\n\n::: column-margin :::\n**TIP**: if_else returns the first value listed (\"Decision\") if the logical expression is true, otherwise it returns the second value listed (\"KO/TKO/Submission\") \n:::\n\nView the \"data1\" data frame and confirm that you understand what the code produced.\n\n## Visualizing the data: the contingency table\n\nA contingency table rows (r) are categories of the first variable and columns (c) those of the second variable.  The \"r x c\" table cells are the counts for each combination of categories.  In our example, both variables have two categories so we have a \"2x2\" contingency table:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(data1$wtClass, data1$decision )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              \n               Decision KO/TKO/Submission\n  Heavyweight       241               570\n  Middleweight      164               334\n```\n\n\n:::\n:::\n\n\n::: column-margin :::\n**TIP**: select the variable from \"data1\" using a \"$\" followed by the name of the variable. \n:::\n\nWe see that among the heavyweight fights, 241 ended with a decision.\n\nThe R package \"DescTools\" we loaded includes a function that will add percentages (by row, column, or total) as well as the totals for rows/columns (known as \"margins\") to the table.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPercTable(data1$wtClass, data1$decision, rfrq = \"010\",\n                     margins = c(1,2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                                         \n                       Decision   KO/TKO/Submission   Sum\n                                                         \nHeavyweight    freq         241                 570   811\n               p.row      29.7%               70.3%     .\n                                                         \nMiddleweight   freq         164                 334   498\n               p.row      32.9%               67.1%     .\n                                                         \nSum            freq         405                 904 1'309\n               p.row      30.9%               69.1%     .\n                                                         \n```\n\n\n:::\n:::\n\n\n::: column-margin :::\n**TIP**: the rfrq option identifies which percentages to display.  A \"1\" in the second position as in our example adds row percentages.  Changing the first position to \"1\" would give total percentages and to the third position column percentages.\n:::\n\n::: column-margin :::\n**TIP**: we provide a vector, c(), with values 1 (row) and 2 (column) of which margins to add to the table.  If we input c(1) we would get only the row totals.\n:::\n\nWe added row percentages; notice that the percentages total to 100\\% for each row of the table, including for the column totals row.\n\n::: {.callout-note  title=\"Exercise 3\"}\n\nUse the contingency tables to answer the following questions:\n\na. How many middleweight fights are included in the sample?\n\nb. How many middleweight fights ended with a KO/TKO/Submission?  What percentage of middleweight fights in the sample does this represent?\n\nc. Which weight class had a higher percentage of fights ending in KO/TKO/Submission?\n\nd. Based on the contingency table, does there appear to be a meaningful association between weight class and how the fight ended?  In other words, is the proportion of fights ending in decision a lot different in the two weight classes? \n\n:::\n\n\n\n## Visualizing the data: Mosaic plot\n\nA Mosaic plot visualizes the contingency table using rectangles with widths proportional to the counts for each category or combination of categories. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggmosaic)\nggplot(data1) + \n  geom_mosaic(aes(x = product(wtClass, decision), fill = wtClass)) +\n  xlab('Decision')\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-note  title=\"Exercise 4\"}\n\nUse the Mosaic plot to answer the following questions (use the contingency table to assist!):\n\na. Are there more fights ending in decision or in KO/TKO/Submission in the data set (how do you know this from the Mosaic plot)?\n\nb. Which weight class appears more likely to have a KO/TKO/Submission?  Does this seem to be a big difference between the weight classes?\n\n:::\n\n\n## Conducting the Chi-square test\n\nWe first write the hypotheses presented earlier for our example:\n\n- $H_0:$  there is no assocation between weight class and whether the fight ended in a decision or not (null hypothesis)\n- $H_a:$  there is an assocation between weight class and whether the fight ended in a decision or not (alternative hypothesis)\n\nThe command \"chisq.test\" with the two variables as inputs performs the Chi-square test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwt_decision.chisq <- chisq.test(data1$wtClass, data1$decision)\n```\n:::\n\n\n::: column-margin :::\n**TIP**: save the test results into an object (here named \"wt_decision.chisq\") in order to later extract all information produced. \n:::\n\n### Observed counts\n\nWe first confirm that the test has the correct data by extracting the \"**observed**\" values.  These should be the same as in the contingency table.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwt_decision.chisq$observed\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              data1$decision\ndata1$wtClass  Decision KO/TKO/Submission\n  Heavyweight       241               570\n  Middleweight      164               334\n```\n\n\n:::\n:::\n\n\n### Expected counts\n\nWe next extract the \"**expected**\" values computed in order to perform the test.  These are values that would be observed if the sample perfectly matched the proportions suggested in the null hypothesis - exactly the same proportions in the two decision categories for each weight class category  (and vice versa).  You will explore this in the next exercise.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nwt_decision.chisq$expected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              data1$decision\ndata1$wtClass  Decision KO/TKO/Submission\n  Heavyweight  250.9206          560.0794\n  Middleweight 154.0794          343.9206\n```\n\n\n:::\n:::\n\n\n::: {.callout-note  title=\"Exercise 5\"}\n\nUse the table of expected counts to answer the following questions:\n\na. Compute the marginal expected counts (i.e. the total expected in rows and columns.  How do these values compare to the marginal observed counts shown in the contingency table?\n\nb. Compute the row percentages for the expected table.  What do you notice about these percentages?  Which row percentages from the contingency table presented earlier do they match?  How does confirm the expected counts are based on the null hypothesis?\n\nc.  How do the expected counts compare to the observed counts?\n\n:::\n\n::: {.callout-important}\n\n## Computing Expected Counts\n\nA simple method to compute the expected count for each cell is the following formula: \n\n$E = (r \\times c) / n$\n\nWhere r is the row total, c the column total, and n the grand total for the entire sample.  \n\nFor fun, use this formula to compute the expected counts for one of the cells in our contingency table!\n\n:::\n\n::: {.callout-important}\n\n## Chi-square test assumption\n\nThe chi-square test is not valid if **expected counts** are too small.  A general rule of thumb is that they should be **greater than or equal to 5**.  \n\nIn our example, the expected counts are all well above 5.  We will explore this issue further in our next example. \n\n:::\n\n### Test results\n\nThe observed counts are unlikely to exactly match the expected (this is a sample).  However, if the null hypothesis is true we would anticipate the reasonably close agreement.  The Chi-square test statistic, $X^2$, measures how well they agree as:\n\n$$X^2 = \\sum \\frac{(O-E)^2}{E}$$\nIn this expression, the $\\sum$ symbol means \"sum\" or add.  The terms added involve the observed (O) and expected (E) counts.  In our case, there are 4 such quantities (one for each cell of the tables).  For example, for the first cell (row 1, column 1) the quantity computed is:\n\n$$\\frac{(241-250.9206)^2}{250.9206} = 0.39$$\n\nWe calculate in similar fashion for the other three cells, and then sum (add) the four values.  The resulting value, 1.3462, is given in the output from the test \"X-squared\".  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nwt_decision.chisq\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  data1$wtClass and data1$decision\nX-squared = 1.3462, df = 1, p-value = 0.2459\n```\n\n\n:::\n:::\n\n\nIf the **observed perfectly matches the expected** in all cells the $X^2$ value would be 0.  Of course, that is unlikely.  However, if the null hypothesis is true, a smaller value is more likely.  But how small is reasonable?  Put another way, how large a value - reflecting big differences in the observed and expected - would make us question whether the null hypothesis is true?\n\nWe answer this question, statistically, by calculating the probability of obtaining a value of $X^2$ of 1.3462 (our observed value) or greater **assuming the null hypothesis is true.** If the null hypothesis is true, the distribution of possible $X^2$ values follows a $\\chi^2$ (\"Chi-squared\") distribution.  There is one parameter for this distribution, known as the \"degrees of freedom\" (df).  For an r x c contingency table:\n\n$$df = (r -1) \\times (c-1)$$ \n\nSince $r = c = 2$ in our example, $df = (2-1) \\times (2-1) = 1$.\n\nWith the distribution defined, we can compute the probability.  The output from R gives us the result as the *p-value* of 0.2459.  If the null hypothesis is true, we have a probability of roughly 0.25 of obtaining observed/expected differences as great as observed in our sample.\n\nTypically, the null hypothesis is \"rejected\" if the p-value is pretty small.  A common cutoff is 0.05.  Since our value is not that small, we cannot reject the null hypothesis.  \n\n\n::: {.callout-important}\n\n## IMPORTANT SUMMARY: Chi-square test conclusion\n\n**We lack evidence to conclude weight class is associated with whether a decision is needed for the fight.**\n\n:::\n\n\n::: {.callout-note  title=\"Exercise 6\"}\n\nThe conclusion from the Chi-square test is that the sample does not provide enough evidence to say weight class is assocated with the decision type.  How does this result compare to your intuition from looking at tables and plots earlier?\n\n:::\n\n# Chi-square Test Issues (Fisher Exact Test) Example\n\n::: {.callout-caution title=\"Research question\"}\n\nIs there difference in the proportion of fights ending in a decision in the four lightest classes (atomweight to bantamweight) in 2023?\n\n:::\n\n\nWe first select the variables of interest, and \"filter\" the data to the categories we wish to compare and the years of interest.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Select, filter, and prepare relevant data for analysis\ndata2 <- mma |> \n  filter(year == 2023) |>\n  select(year, wtClass, decision_group) |> \n  filter(wtClass == \"Flyweight\" | \n           wtClass == \"Bantamweight\" |\n           wtClass == \"Strawweight\" |\n           wtClass == \"Atomweight\"  ) |> \n  mutate(decision = if_else(decision_group == \"Decision\", \"Decision\",\n                            \"KO/TKO/Submission\"))\n```\n:::\n\n\nWe again visualize the data.  We quickly observe that there is not a lot of data for the two lightest weight classes, atomweight and strawweight.  In fact, neither category had a fight which did not end in decision.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggmosaic)\nggplot(data2) + \n  geom_mosaic(aes(x = product(wtClass, decision), fill = wtClass)) +\n  xlab('Decision')\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\n## Chi-square Test\n\nWe can proceed with the Chi-square test.  However, notice that R responds with a warning message.  The test results are still produced and in this case we again cannot conclude evidence of an association (p = 0.1851).  Notice the degrees of freedom for this example.  With 4 weight class categories, we have $(4-1)\\times(2-1) = 3$ degrees of freedom for the test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwt_decision2.chisq <- chisq.test(data2$wtClass, data2$decision)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in chisq.test(data2$wtClass, data2$decision): Chi-squared approximation\nmay be incorrect\n```\n\n\n:::\n\n```{.r .cell-code}\nwt_decision2.chisq \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  data2$wtClass and data2$decision\nX-squared = 4.8241, df = 3, p-value = 0.1851\n```\n\n\n:::\n:::\n\n\nThe warning message is due to the assumption about expected cell counts.  These values are well below the rule of thumb of five for both categories in the atomweight and strawweight classes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwt_decision2.chisq$expected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              data2$decision\ndata2$wtClass   Decision KO/TKO/Submission\n  Atomweight   0.4848485         0.5151515\n  Bantamweight 7.2727273         7.7272727\n  Flyweight    7.7575758         8.2424242\n  Strawweight  0.4848485         0.5151515\n```\n\n\n:::\n:::\n\n\n## Fisher Exact Test\n\nWhen the assumption for the Chi-square test is not met, all is not lost!  We can instead compute the p-value \"exactly\" using probability theory (the \"hypergeometric\" distribution is used, but we will omit the details).\n\nThe Fisher's Exact Test assumes the row and column totals are fixed, then calculates the probability of a particular set of cell counts, then figures out all possible tables that could be constructed given the fixed totals, and calculates probabilities for each of these tables. The test determines which of these tables are extreme or more extreme than the table observed, and sums up the probabilities for the table seen and the more extreme tables to get the p-value.  \n\nThe hypotheses for this test are the same as for the Chi-square test:\n\n$H_0$: Weight class and the fight decision are not associated.  \n$H_a$: Weight class and the fight decision are associated.\n\nThe command is changed to \"fisher.test\", but the general format of the command and output is unchanged.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwt_decision2.fisher <- fisher.test(data2$wtClass, data2$decision)\nwt_decision2.fisher\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tFisher's Exact Test for Count Data\n\ndata:  data2$wtClass and data2$decision\np-value = 0.09378\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\nThe test returned a p-value of 0.09378.  Our conclusion then after performing a Fisher's Exact Test is again we do not have evidence to suggest that weight class and fight decision are associated (p = 0.09). In other words, we fail to reject our null hypothesis.  \n\nNotice that the p-value is changed by a fair amount in this example even though the conclusion is unchanged.  The issue with the Chi-square assumption had an impact on the calculation in this case.\n\n::: {.callout-important}\n\n## Fisher Exact Test issues\n\nThe Fisher Exact test requires a great deal of computation.  Every possible table of counts must be formed.  For larger tables, this computation (even with the advances in computing power) might not alway be feasible.\n\nChi-square tests notoriously lack \"power\" (they may not produce statistically significant results even when there is an association).  The exact test power is often even lower.  In fact, in some situations with small samples there is no chance the test could lead to rejecting the null hypothesis!\n\n:::\n\n# Case study 1: Interpreting Results\n\n## Examining the Sample\n\nBelow we select a larger sample of years and weight classes, and produce the output shown in previous examples.  Use the output to answer the questions in the exercise.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Select, filter, and prepare relevant data for analysis\ndata3 <- mma |> \n  filter(year >= 2020) |>\n  filter(wtClass %in% c(\"Strawweight\", \"Flyweight\",\n                              \"Bantamweight\", \"Welterweight\",\n                              \"Middleweight\", \"Heavyweight\"))  |> select(year, wtClass, decision_group) |> \n  mutate(decision = if_else(decision_group == \"Decision\",\n                            \"Decision\",\n                            \"KO/TKO/Submission\"))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(data3$wtClass, data3$decision)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              \n               Decision KO/TKO/Submission\n  Bantamweight      302               350\n  Flyweight         248               263\n  Heavyweight       241               570\n  Middleweight      164               334\n  Strawweight       123                80\n  Welterweight      270               440\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggmosaic)\nggplot(data3) + \n  geom_mosaic(aes(x = product(wtClass, decision), fill = wtClass)) +\n  xlab('Decision')\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-note  title=\"Exercise 7\"}\n\na.  What is the research question for the data selected?\n\nb.  What are the degrees of freedom that will be used in a Chi-square test with this sample?\n\nc.  Do you think the Chi-square test assumption will be a concern with this data?  Explain.\n\nd.  Does the data seem to suggest an association?  Explain.\n\n:::\n\n## Conducting the Test\n\nAgain, we provide output from a test.  Use this to answer the exercise questions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncase1.chisq <- chisq.test(data3$wtClass, data3$decision)\ncase1.chisq$expected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              data3$decision\ndata3$wtClass   Decision KO/TKO/Submission\n  Bantamweight 259.64431          392.3557\n  Flyweight    203.49424          307.5058\n  Heavyweight  322.96248          488.0375\n  Middleweight 198.31728          299.6827\n  Strawweight   80.84018          122.1598\n  Welterweight 282.74151          427.2585\n```\n\n\n:::\n\n```{.r .cell-code}\ncase1.chisq\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  data3$wtClass and data3$decision\nX-squared = 109.58, df = 5, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n::: {.callout-note  title=\"Exercise 8\"}\n\na.  What hypotheses for the test?\n\nb.  What are your conclusions based on the test?\n\nc.  Is the test appropriate (assumptions met) or is another test required?\n\n:::\n\n## Examining the Results\n\nThe statistically significant results from the test in this case study beg some  questions. \n\n- (1) Which weight classes and which decision groups differ?\n- (2) We achieved statistical significance, but perhaps this is simply do to the very large sample size.  Is there practical significance?  \n\nWe can do an informal inspection of the observed and expected values (and also consider the visualization).  We have already produced the observed (contingency) and expected tables.  We add the row percentages below. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nPercTable(data3$wtClass, data3$decision, rfrq = \"010\",\n                     margins = c(1,2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                                         \n                       Decision   KO/TKO/Submission   Sum\n                                                         \nBantamweight   freq         302                 350   652\n               p.row      46.3%               53.7%     .\n                                                         \nFlyweight      freq         248                 263   511\n               p.row      48.5%               51.5%     .\n                                                         \nHeavyweight    freq         241                 570   811\n               p.row      29.7%               70.3%     .\n                                                         \nMiddleweight   freq         164                 334   498\n               p.row      32.9%               67.1%     .\n                                                         \nStrawweight    freq         123                  80   203\n               p.row      60.6%               39.4%     .\n                                                         \nWelterweight   freq         270                 440   710\n               p.row      38.0%               62.0%     .\n                                                         \nSum            freq       1'348               2'037 3'385\n               p.row      39.8%               60.2%     .\n                                                         \n```\n\n\n:::\n:::\n\n   \n\n::: {.callout-note  title=\"Exercise 9\"}\n\na.  What categories are different and likely led to the statistically signficant result?\n\nb.  How easy is it to identify the important differences in observed and expected values (consider this question in a table with more than two decision categories!)?\n\n:::\n\n### Residuals\n\nWhen we have a high number of rows and columns it is difficult to see if there are practical differences between certain cells. This may be achievable with a 2x2 table, but is much more difficult with larger tables. To help with this problem, we can calculate the **Pearson standardized residuals** which help identify cells we should investigate. \n\nThe formula for the Pearson residuals is:\n\n$$\\frac{(O-E)}{\\sqrt(E)}$$\n\nNotice this is the square root of the \"contribution\" of each cell to the overall test statistic $X^2$.  Essentially, the formula identifies cells that have large differences between observed and expected (the $(O-E)$ in the formula) but \"standardizes\" these differences (the $sqrt(E)$ in the formula).\n\nOne way to think about the standardization is to consider a simple example.  Suppose we have two cells with $O-E = 2$.  However, one cell has an expected count of 10 and the other an expected count of 1,000.  In the first case, the $O-E$ difference is 20\\% of the expected value.  In the second, it is only 0.2% which is actually a small amount. The standardization basically puts these on the same scale.\n\nStandardized residuals roughly follow a \"normal distribution\" which means we would expect approximately 95\\% of the values to between -2 and 2 and 99\\% between -3 and 3.  Thus, values outside these ranges are somewhat unusual and cells that may contribute to a statistical association.\n\nWe can output the residuals from the Chi-square test in similar fashion to the expected counts:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncase1.chisq$residuals\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              data3$decision\ndata3$wtClass    Decision KO/TKO/Submission\n  Bantamweight  2.6285868        -2.1383153\n  Flyweight     3.1198964        -2.5379882\n  Heavyweight  -4.5607794         3.7101246\n  Middleweight -2.4368714         1.9823578\n  Strawweight   4.6890531        -3.8144733\n  Welterweight -0.7577501         0.6164182\n```\n\n\n:::\n:::\n\n\n::: {.callout-note  title=\"Exercise 10\"}\n\na.  Based on the residuals what categories are different and likely led to the statistically signficant result?\n\nb.  Considering the categories you identified, do the differences seem practically meaningful?  Explain.\n\n:::\n\n\n# Case study 2: Putting it all together\n\n::: {.callout-important}\n\n## IMPORTANT SUMMARY\n\nChi-square and Fisher Exact tests (if appropriate) are used in exploring associations between two **categorical variables**.  Basic steps in these tests include:\n\n1. Formulating a research question.\n2. Identifying variables in the data set that are relevant to answering the research question.\n3. If the variables are both categorical, proceed with the Chi-square analysis.\n4. Visualize the data using contingency tables and Mosaic plots.\n5. Perform the Chi-square test (check the assumption of expected counts >5 and use Fisher exact test if not met).\n6. Reach a conclusion based on the test.  \n7. If a statistically significant association is found, examine the residuals to help identify categories that differ and consider if the differences are practically meaningful.\n\nIn the following exercise, copy/paste/tweak code to perform analysis using these steps.\n\n:::\n\n::: {.callout-note  title=\"Exercise 11\"}\n\nMMA leadership is interested in whether there is a difference based on sex in how fights ended (all possible categories, not just decision or not) in 2023.  Perform an analysis to provide them with insights related to this question.  If there are differences, describe them for the leadership team.  *Hint: consider the variables \"p1_sex\" and \"decision_group\" for this question.*\n\n:::\n\n::: {.callout-note  title=\"Exercise 12\"}\n\nFormulate an additional question that involves categorical variables available in the data set and perform the analysis to address the question.\n\n:::\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}